<?php if(App::config('dev')):?>
    
    <div class="grid-x grid-padding-x" style="margin-top: 150px;">                   
        <img src="<?=App::config('url')?>public/img/error404.svg" id="error404">
    </div>

    <div class="grid-x grid-padding-x" style="text-align: center">
        <h1 class="pozdrav">Ups, malo si se prebrijao :) <br/> Primiri se i kreni <a href="<?=App::config('url')?>">ispočetka</a></h1>
    </div>
    
<?php endif;?>