<div class="grid-x grid-padding-x" style="text-align: center">
   <h1 class="pozdrav">Dobrodošli!</h1>
</div>
<div class="grid-x grid-padding-x" style="text-align: center" id="pocetna">
    <div class="large-3 medium-4 cell"  id="bass">                    
        <img src="<?=App::config('url')?>public/img/bass.svg">                                      
     </div>
     <div class="large-3 medium-4 cell" style="text-align: center" id="bubanj">                    
        <img src="<?=App::config('url')?>public/img/bubanj.svg">                                    
     </div>
     <div class="large-3 medium-4 cell" style="text-align: center" id="gitara">                    
        <img src="<?=App::config('url')?>public/img/gitara.svg">                                    
     </div>
</div>
