<div class="grid-x grid-padding-x" style="text-align: center">
   <h1 class="pozdrav" id="pozdrav">Dobrodošli!</h1>
</div>
<div class="grid-x grid-padding-x" style="text-align: center" id="pocetna">
    <div class="large-4 cell small-2 cell">                    
        <img src="<?=App::config('url')?>public/img/bass.svg" id="bass">                                      
     </div>
     <div class="large-4 cell small-2 cell" style="text-align: center" >                    
        <img src="<?=App::config('url')?>public/img/bubanj.svg" id="bubanj">                                    
     </div>
     <div class="large-4 cell small-2 cell" style="text-align: center">                    
        <img src="<?=App::config('url')?>public/img/gitara.svg" id="gitara">                                    
     </div>
</div>
