<div class="grid-x grid-padding-x">
    <?php include 'dodajNovi.phtml'; ?>
    <?php foreach($proizvodi as $proizvod): ?>
        <div class="large-3 medium-4 cell">
            <div class="callout" id="proizvod">

                <h2 style="font-size: 2rem; font-family: Hubballi;">
                    <?=$proizvod->naziv;?>
                </h2>
                
                <img src="<?=App::config('url')?>public/img/proizvodi/<?=$proizvod->sifra . '.webp'?>" class="proizvod-slika">
                
                <h3 style="font-size: 1.5rem; font-family: Hubballi;">
                    <?=$proizvod->izvodac;?>
                </h3>

                <h4 style="font-size: 1rem; font-family: Hubballi;">
                    <?=$proizvod->cijena;?>
                </h4>

                <a href="<?=App::config('url')?>proizvod/promjena/<?=$proizvod->sifra?>">
                    <i title="Promijeni" 
                        class="fas fa-edit"></i>
                </a>

                <?php if($proizvod->kosarica==0): ?>
                    <a onclick="return confirm('Sigurno obrisati?')" style="margin-left: 20px;" href="<?=App::config('url')?>proizvod/brisanje/<?=$proizvod->sifra?>">
                        <i style="color: red;" title="Obriši" 
                            class="fas fa-trash-alt"></i>
                    </a>
                <?php else: ?>
                    <i style="margin-left: 20px; color: gray;" title="Nije moguće brisanje jer se nalazi u aktivnoj košarici" 
                            class="fas fa-trash-alt"></i>
                <?php endif; ?>          
            </div>        
        </div>
    <?php endforeach; ?>

    <?php include 'dodajNovi.phtml'; ?>
</div>