<form action="<?=App::config('url')?>proizvod/dodajNovi" method="post" class="forma-unos">

    <fieldset>
        <legend>Dodavanje novog proizvoda</legend>

    <label for="zanr" style="color: white;">Žanr</label>
    <input type="text" name="zanr" id="zanr" value="<?= $proizvod->zanr ?>">

    <label for="izvodac" style="color: white;">Izvođač</label>
    <input type="text" name="izvodac" id="izvodac" value="<?= $proizvod->izvodac ?>">

    <label for="naziv" style="color: white;">Naziv</label>
    <input type="text" name="naziv" id="naziv" value="<?= $proizvod->naziv ?>">

    <label for="cijena" style="color: white;">Cijena</label>
    <input type="text" name="cijena" id="cijena" value="<?= $proizvod->cijena ?>">

    <label for="izdavackaKuca" style="color: white;">Izdavačka kuća</label>
    <input type="text" name="izdavackaKuca" id="izdavackaKuca" value="<?= $proizvod->izdavackaKuca ?>">

    <label for="zaliha" style="color: white;">Zaliha</label>
    <input type="number" name="zaliha" id="zaliha" pattern="[0-9]{10}" value="<?= $proizvod->zaliha ?>">

    <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" href="<?=App::config('url')?>proizvod/index" id="odustani-dugme">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="Dodaj novi proizvod" id="potvrdi-dugme">
            </div>
    </div>

    <?=$poruka?>

    </fieldset>

</form>