<form action="<?=App::config('url')?>proizvod/promijeni" method="post" id="program">

    <fieldset>
        <legend>Promjena postojećeg proizvoda</legend>

    <label for="zanr">Žanr</label>
    <input type="text" name="zanr" id="zanr" value="<?= $proizvod->zanr ?>">

    <label for="izvodac">Izvođač</label>
    <input type="text" name="izvodac" id="izvodac" value="<?= $proizvod->izvodac ?>">

    <label for="naziv">Naziv</label>
    <input type="text" name="naziv" id="naziv" value="<?= $proizvod->naziv ?>">

    <label for="cijena">Cijena</label>
    <input type="text" name="cijena" id="cijena" value="<?= $proizvod->cijena ?>">

    <label for="izdavackaKuca">Izdavačka kuća</label>
    <input type="text" name="izdavackaKuca" id="izdavackaKuca" value="<?= $proizvod->izdavackaKuca ?>">

    <label for="zaliha">Zaliha</label>
    <input type="number" name="zaliha" id="zaliha" pattern="[0-9]{10}" value="<?= $proizvod->zaliha ?>">

    <input type="hidden" name="sifra" value="<?=$proizvod->sifra?>">

    <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" href="<?=App::config('url')?>proizvod/index">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="Promijeni">
            </div>
    </div>

    <?=$poruka?>

    </fieldset>

</form>