<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('naslovApp')?></div>
</div>

<div class="top-bar" id="example-menu" style="background-color: black">
  <div class="top-bar-left" style="background-color: black">
    <ul class="dropdown menu" data-dropdown-menu style="background-color: black">
      <li class="menu-text"><?=App::config('naslovApp')?></li>
      <li><a href="<?=App::config('url')?>"><i class="fas fa-home" style="color: white"></i></a></li>
      <?php if(App::autoriziran()): ?>
        <li><a href="<?=App::config('url')?>nadzornaploca/index">Nadzorna ploča</a></li>
      <?php endif; ?>
      <?php if(App::autoriziran()): ?>
        <li><a href="#">Programi</a>
          <ul class="submenu menu vertical" data-submenu>
            <li><a href="<?=App::config('url')?>kupac/index">Kupac</a></li>
            <li><a href="<?=App::config('url')?>proizvod/index">Proizvod</a></li>
            <li><a href="<?=App::config('url')?>narudzba/index">Narudžba</a></li>
            <li><a href="<?=App::config('url')?>kosarica/index">Košarica</a></li>
          </ul>
        </li>
      <?php endif; ?>  
    </ul>
  </div>
  <div class="top-bar-right" style="background-color: black">
    <ul class="menu">
      <li style="background-color: black">
        <?php if(App::autoriziran()): ?>
          <a class="prijava-dugme" href="<?=App::config('url')?>login/odjava">Odjava <?php echo $_SESSION['autoriziran']->ime ?></a>
        <?php else: ?>
          <a class="prijava-dugme" href="<?=App::config('url')?>login/index">Prijava</a>
        <?php endif; ?>
      </li>
    </ul>
  </div>
</div>